# Generated by Django 5.2.15 on 2026-09-10 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='templeevent',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='templeevent',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.templeevent'),
        ),
    ]
