# Generated by Django 5.2.15 on 2026-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('devotee', 'Devotee'), ('pending_temple_admin', 'Pending Temple Admin'), ('temple_admin', 'Temple Admin'), ('temple_member', 'Temple Member'), ('super_admin', 'Super Admin')], default='devotee', max_length=30),
        ),
    ]
