# Generated by Django 5.2.15 on 2026-07-05 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_deity', models.CharField(blank=True, max_length=100)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='temples/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_temples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TempleFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='temples.temple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_temples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'temple')},
            },
        ),
        migrations.CreateModel(
            name='TempleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('editor', 'Editor')], default='editor', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='temples.temple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temple_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('temple', 'user')},
            },
        ),
    ]
