# Generated by Django 5.2.15 on 2026-07-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0002_templerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='templerequest',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='templerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='templerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
