# Generated by Django 5.2.15 on 2026-07-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0003_temple_district_templerequest_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_name', models.CharField(blank=True, default='', max_length=150)),
                ('region_name', models.CharField(blank=True, default='', max_length=150)),
                ('division_name', models.CharField(blank=True, default='', max_length=150)),
                ('office_name', models.CharField(max_length=150)),
                ('pincode', models.CharField(db_index=True, max_length=6)),
                ('office_type', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=30)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['pincode', 'office_name'],
                'indexes': [models.Index(fields=['state', 'district'], name='postal_state_dist_idx')],
                'constraints': [models.UniqueConstraint(fields=('pincode', 'office_name', 'district', 'state'), name='unique_pincode_office_location')],
            },
        ),
    ]
