# Generated by Django 5.2.15 on 2026-07-19 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0004_pincodelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='pincode_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temples', to='temples.pincodelocation'),
        ),
        migrations.AddField(
            model_name='templerequest',
            name='pincode_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temple_requests', to='temples.pincodelocation'),
        ),
    ]
