# Generated by Django 5.2.15 on 2026-07-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0005_temple_pincode_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
