# Generated by Django 5.2.15 on 2026-07-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0006_templerequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='templerequest',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templerequest',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templerequest',
            name='temple_image',
            field=models.ImageField(blank=True, null=True, upload_to='temple_requests/temple_images/'),
        ),
    ]
