# Generated by Django 5.2.15 on 2026-07-25 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0009_backfill_temple_workspaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_values', models.JSONField(default=dict, help_text='Snapshot of the approved temple values when this request was submitted.')),
                ('requested_changes', models.JSONField(default=dict, help_text='Only the sensitive temple fields requested for change.')),
                ('reason', models.TextField()),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='temple_change_requests/proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temple_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_temple_change_requests', to=settings.AUTH_USER_MODEL)),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='temples.temple')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['temple', 'status'], name='temple_change_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('temple',), name='uniq_pending_temple_change_req')],
            },
        ),
    ]
