# Generated by Django 5.2.15 on 2026-07-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0012_templechangerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempleChangeRequest',
        ),
    ]
