# Generated by Django 5.2.15 on 2026-07-25 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0013_delete_templechangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempleVerifiedEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reason', models.TextField()),
                ('status', models.CharField(choices=[('access_pending', 'Edit Access Pending'), ('edit_allowed', 'Edit Access Approved'), ('changes_pending', 'Changes Pending Approval'), ('approved', 'Changes Approved'), ('rejected', 'Rejected')], db_index=True, default='access_pending', max_length=30)),
                ('original_name', models.CharField(max_length=255)),
                ('original_pincode', models.CharField(blank=True, default='', max_length=10)),
                ('original_city', models.CharField(blank=True, default='', max_length=100)),
                ('original_district', models.CharField(blank=True, default='', max_length=100)),
                ('original_state', models.CharField(blank=True, default='', max_length=100)),
                ('original_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('original_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('proposed_name', models.CharField(blank=True, default='', max_length=255)),
                ('proposed_pincode', models.CharField(blank=True, default='', max_length=10)),
                ('proposed_city', models.CharField(blank=True, default='', max_length=100)),
                ('proposed_district', models.CharField(blank=True, default='', max_length=100)),
                ('proposed_state', models.CharField(blank=True, default='', max_length=100)),
                ('proposed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('proposed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('access_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('final_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_stage', models.CharField(blank=True, choices=[('access_request', 'Edit Access Request'), ('submitted_changes', 'Submitted Changes')], default='', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verified_edit_access_requests', to=settings.AUTH_USER_MODEL)),
                ('final_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verified_temple_changes', to=settings.AUTH_USER_MODEL)),
                ('original_pincode_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='temples.pincodelocation')),
                ('proposed_pincode_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='temples.pincodelocation')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_verified_temple_edits', to=settings.AUTH_USER_MODEL)),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_edit_requests', to='temples.temple')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['temple', 'status'], name='temple_edit_status_idx'), models.Index(fields=['status', 'created_at'], name='edit_request_queue_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['access_pending', 'edit_allowed', 'changes_pending'])), fields=('temple',), name='unique_active_verified_edit_request_per_temple')],
            },
        ),
    ]
