# Generated by Django 5.2.15 on 2026-07-26 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0014_templeverifiededitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='templerequest',
            name='resubmitted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='temples.templerequest'),
        ),
    ]
