# Generated by Django 5.2.15 on 2026-07-05 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temples', '0002_templerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempleUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('update_type', models.CharField(choices=[('general', 'General'), ('pooja', 'Pooja'), ('seva', 'Seva'), ('annadanam', 'Annadanam'), ('notice', 'Notice'), ('festival', 'Festival')], default='general', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='temple_updates/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_temple_updates', to=settings.AUTH_USER_MODEL)),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='temples.temple')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
