# Generated by Django 5.2.15 on 2026-07-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templeupdate',
            name='image',
        ),
        migrations.AddField(
            model_name='templeupdate',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templeupdate',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
