# Generated by Django 5.2.15 on 2026-07-27 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temples', '0015_templerequest_resubmitted_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('temple_request_approved', 'Temple Request Approved'), ('temple_request_rejected', 'Temple Request Rejected'), ('verified_edit_access_approved', 'Verified Edit Access Approved'), ('verified_edit_access_rejected', 'Verified Edit Access Rejected'), ('verified_edit_changes_approved', 'Verified Edit Changes Approved'), ('verified_edit_changes_rejected', 'Verified Edit Changes Rejected')], max_length=50)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('reference_type', models.CharField(blank=True, choices=[('temple_request', 'Temple Request'), ('verified_edit_request', 'Verified Edit Request')], default='', max_length=40)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('web_action_url', models.CharField(blank=True, default='', max_length=255)),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('temple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temple_notifications', to='temples.temple')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_user_read_created_idx'), models.Index(fields=['reference_type', 'reference_id'], name='notif_reference_lookup_idx')],
            },
        ),
    ]
